@startuml
title <size:24>Ants</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("AntFarm_boundary", "AntFarm", $tags="") {
  Container_Boundary("AntFarm.AntFarm_boundary", "AntFarm", $tags="") {
    Component(AntFarm.AntFarm.World, "World", $techn="Module", $descr="", $tags="", $link="")
    Component(AntFarm.AntFarm.Colony, "Colony", $techn="Module", $descr="", $tags="", $link="")
    Component(AntFarm.AntFarm.Food, "Food", $techn="Module", $descr="", $tags="", $link="")
    Component(AntFarm.AntFarm.Predators, "Predators", $techn="Module", $descr="", $tags="", $link="")
    Component(AntFarm.AntFarm.Ants, "Ants", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(AntFarm.AntFarm.Predators, AntFarm.AntFarm.World, "uses", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Food, AntFarm.AntFarm.World, "uses", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Ants, AntFarm.AntFarm.Colony, "listens to", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Ants, AntFarm.AntFarm.Predators, "listens to", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Ants, AntFarm.AntFarm.World, "uses", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Ants, AntFarm.AntFarm.Colony, "uses", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Ants, AntFarm.AntFarm.Food, "uses", $techn="", $tags="", $link="")
Rel(AntFarm.AntFarm.Colony, AntFarm.AntFarm.World, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml